
<?php
    $title = 'Criar sala de aula';
    $this->headTitle($title);
?>
<main>
    <div class="jumbotron">
        <div class='row mt-4'>
            <div id='opend-rooms' class='col-sm-12 col-md-6'>
                <h1>Bem vindo ao <span class="zf-green">WebTv</span></h1>
                <h4>Salas disponíveis</h4>
                <hr>
                <div id='public-conference'>
                    <div class="text-center zf-green mt-5">
                        <div class="h6">Encontrando salas...</div>
                        <i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
                        <span class="sr-only">Aguarde...</span>
                    </div>
                    <!--Salas disponíveis-->
                </div>
            </div>
            <div id='teacher-access' class='col-sm-12 col-md-6'>
                <div class='card bg-light'>
                    <h5 class='card-header'>
                        <i class='fa fa-desktop'></i> Nova sala de aula:
                    </h5>
                    <div class='card-body'>
                        <div class='card-title'>
                            <h3 class='panel-heading'><?php $this->escapeHtml($title) ?></h3>
                        </div>
                        <div class='form-group'>
                            <?php
                                $form->setAttribute('action', $this->url('classroom', ['action'=>'index']));
                                $form->prepare();

                                echo $this->form()->openTag($form);
                                echo $this->formHidden($form->get('id'));
                                echo "<i class='fa fa-book'></i> ";
                                echo $this->formRow($form->get('materia'));
                                echo '<br>';
                                echo "<i class='fa fa-tag'></i> ";
                                echo $this->formRow($form->get('aula'));
                                echo '<br>';
                            ?>
                            <hr>
                            <div class='text-right'>
                                <?php
                                    echo $this->formSubmit($form->get('submit'));
                                    echo $this->form()->closeTag();
                                ?>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        <div class=''>
            <!--Video Panel-->
            <div id='video-panel' class='row d-none'>
                <!--Painel de Debug-->
                <div class='hidden-panel'>
                    <input type='hidden' id='connected-class' readonly />
                    <input type='hidden' id='connected-content' readonly />
                    <input type='hidden' id='current-user' value='User' readonly />
                </div>
                <div class='col-sm-12 col-md-8'>
                    <!--Card de vídeo e chat-->
                    <div class='card'>
                        <div id='class-suptitle' class='card-header'>
                            <i class="fa fa-circle zf-green"></i>
                            <span id='class-title'>
                                <!--Título da aula - Matéria (Assunto)-->
                            </span>
                        </div>
                        <div class='card-body'>
                            <div class='row'>
                                <div class='col-sm-12'>
                                    <div id='room-urls'>
                                        <!--Definições da Sala-->
                                    </div>
                                    <div id='main-video' class='inroom mainView'>
                                        <!--Vídeo principal-->
                                        <div id='div-connect'>
                                            <div class='h6 zf-green text-center'>
                                                Conectando...
                                            </div>
                                            <div class="progress">
                                                <div class="progress-bar bg-success progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="100" aria-valuemin="100" aria-valuemax="100" style="width: 100%"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!--Formação de chat-->
                                <div class='col-sm-12'>
                                    <div class='form-row mt-4 mb-4'>
                                        <div class='col-10'>
                                            <!--Input de mensagem-->
                                            <input type='text' id='text-message' class='form-control w-100' />
                                        </div>
                                        <div class='col text-right'>
                                            <!--Botão de envio-->
                                            <a id='send-message-btn' class='btn btn-info' style='width:100%;'><i class='fa fa-send text-light'></i></a>
                                        </div>
                                    </div>
                                    <div class='card light-bg'>
                                        <!--Output de mensagem-->
                                        <textarea class='form-control bg-light' disabled rows='6' id='chat-panel'></textarea>
                                    </div>
                                </div>    
                            </div>
                        </div>
                        <div id='teacher-name' class='card-footer text-center'>
                            <!--Nome do professor-->
                        </div>
                    </div>
                </div>
                <!--Painel com os vídeos dos espectadores-->
                <div class='col-sm-12 col-md-4' style='display:block;'>
                    <div id='class-video' class='inroom otherView'>
                        <!--Outros vídeos-->
                    </div>
                </div>
            </div> 
        </div>
    </div>

</main>
