<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('WebTv Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/getHTMLMediaElement.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/application.js'))
            ->prependFile($this->basePath('js/RTCMultiConnection.min.js'))
            ->prependFile($this->basePath('js/getHTMLMediaElement.js'))
            ->prependFile($this->basePath('js/socket.io.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="<?= $this->url('home') ?>">
                            WebTv
                        </a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                            <li class="nav-item active">
                                <a class="nav-link" href="<?= $this->url('home') ?>"><i class='fa fa-home'></i> Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('classroom') ?>">Sala de Aula</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div>
                <img id='backgroundLayer' src="<?= $this->basePath('img/skyline.jpg')?> "/>
            </div>
        </header>

        <div class="container">
            <?= $this->content ?>
            <footer class='navbar navbar-dark bg-dark fixed-bottom text-light'>
                <p>WebTv &copy; <?= date('Y') ?> Intelit - Todos os direitos reservados.</p>
            </footer>
        </div>

        <?= $this->inlineScript() ?>
    </body>
</html>
