<?php
    $title = 'Cadastro de Usuários';
    $this->headTitle($title);
?>
<main>
    <div class="jumbotron">
        <h1>Bem vindo ao <span class="zf-green">WebTv</span></h1>
        <div class='row mt-4'>
            <div id='user-access' class='col-sm-12 col-md-6 offset-md-3'>
                <div class='card bg-light'>
                    <h5 class='card-header'>
                        <i class='fa fa-user-plus'></i> Cadastro de novo usuário
                    </h5>
                    <div class='card-body'>
                        <div class='card-title'>
                            <h3 class='panel-heading'><?php $this->escapeHtml($title) ?></h3>
                        </div>
                        <div class='form-group'>
                            <?php
                                $form->setAttribute('action', $this->url('user', ['action'=>'add']));
                                $form->prepare();

                                echo $this->form()->openTag($form);
                                echo $this->formHidden($form->get('id'));

                                echo "<i class='fa fa-vcard'></i> ";
                                echo $this->formRow($form->get('matricula'));
                                echo '<br>';

                                echo "<i class='fa fa-user fa-lg'></i> ";
                                echo $this->formRow($form->get('nome'));
                                echo '<br>';

                                echo "<i class='fa fa-lock fa-lg'></i> ";
                                echo $this->formRow($form->get('senha'));
                                echo '<br>';

                                echo "<i class='fa fa-lock fa-lg'></i> ";
                                echo $this->formRow($form->get('confirmsenha'));
                                echo '<br>';

                                echo "<i class='fa fa-envelope'></i> ";
                                echo $this->formRow($form->get('email'));
                                echo '<br>';

                                echo "<i class='fa fa-building'></i> ";
                                echo $this->formRow($form->get('codescola'));
                                echo '<br>';

                                echo "<i class='fa fa-graduation-cap'></i> ";
                                echo $this->formRow($form->get('escola'));
                                echo '<br>';

                                echo "<i class='fa fa-users'></i> ";
                                echo $this->formRow($form->get('grupo'));
                                echo '<br>';
                            ?>
                            <hr>
                            <div class='text-right'>
                                <?php
                                    echo $this->formSubmit($form->get('submit'));
                                    echo $this->form()->closeTag();
                                ?>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        
    </div>

</main>

