<?php
    $title = 'Acesso ao WebTv';
    $this->headTitle($title);
?>
<main>
    <div class="jumbotron">
        <h1>Bem vindo ao <span class="zf-green">WebTv</span></h1>
        <hr>
        <div class='row'>
            <div class='col-sm-12 col-md-6 offset-md-6'>
                <div class='card'>
                    <h5 class='card-header'><i class='fa fa-sign-in'></i> Acesso</h5>
                    <div class='card-body'>
                        <?php
                            $form->setAttribute('action', $this->url('application', ['action'=>'index']));
                            $form->prepare();

                            echo $this->form()->openTag($form);
                                            
                            echo "<i class='fa fa-user fa-lg'></i> ";
                            echo $this->formRow($form->get('usuario'));
                            echo '<br>';

                            echo "<i class='fa fa-lock fa-lg'></i> ";
                            echo $this->formRow($form->get('senha'));
                            echo '<br>';              
                        ?>
                        <hr>
                        <div class='text-right'>
                            <?php
                                echo $this->formSubmit($form->get('submit'));
                                echo $this->form()->closeTag();
                            ?>
                            <div class='d-none'>
                                <input type='hidden' id='btn-join-as-teacher' />
                                <input type='hidden' id='room-id' />
                                <input type='hidden' id='public-conference' />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>

